name: Validate Terraform Code
on:
  workflow_dispatch:
  
  push:
    branches:
      - '**'
      - '!prod'
      - '!stage'
      - '!test'
      - '!develop'

jobs:
  integrate_terraform:
    name: Integrate Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Derive Terraform Working Dir
        run: |
          if [ -z "$TF_WORKING_DIR" ] ; then
            if [ -d terraform ] ; then
              echo "TF_WORKING_DIR=`echo 'terraform'`" >> $GITHUB_ENV
            else
              echo "TF_WORKING_DIR=`echo '.'`" >> $GITHUB_ENV
            fi
          fi

      - name: Terraform Format
        id: fmt
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} fmt -check

      - name: Terraform Log Version
        id: version
        run: terraform -version

      - name: Terraform Init
        id: init
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} init -backend=false

      - name: Terraform Validate
        id: Validate
        run: terraform -chdir=${{ env.TF_WORKING_DIR }} validate -no-color
        env:
          AWS_DEFAULT_REGION: us-east-1
